### ISSUE TITLE
ERC827 token issue

### ISSUE THREAD

**Issue by Dohko** [MainframeHQ/contracts#27]
Hi!

Mainframe token is ERC827 based token contract according to your documentation.
Maybe you should to fix that because this seems unsafe https://github.com/ethereum/EIPs/issues/827#issuecomment-397857455 . Openzeppelin removed its support last week.

Good luck!

**Comment by howleysv** [comment]
Hi @Dohko, we really appreciate the heads-up on this! We gave you a shout-out in our blog post detailing the token contract issue: https://blog.mainframe.com/important-mft-contract-redeployed-4f0b0bd8dc3b

We have modified our token contract to remove ERC827 and just to the base ERC20 logic.
